config/routes.rb
Rails.application.routes.draw do
  get 'profiles' => 'profiles#index'
  get 'profiles/:id' => 'profiles#show', as: :profile
  
  resources :squeaks do
    resource :likes
  end
  
  resources :relationships, only: [:create, :destroy]
  
  devise_for :users
  
  root 'squeaks#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :squeak
end


# == Schema Information
#
# Table name: likes
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  squeak_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :user #this is the current user
    belongs_to :friend, class_name: "User" #we're telling them that a friend is just another User
    
end
# == Schema Information
#
# Table name: relationships
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  friend_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/squeak.rb
class Squeak < ApplicationRecord
  belongs_to :user
  has_many :likes
  validates :message, presence: true, length: { maximum: 140, too_long: 'Squeaks are limited to 140 characters. Edit it down.'}
end


# == Schema Information
#
# Table name: squeaks
#
#  id         :integer          not null, primary key
#  message    :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_squeaks_on_user_id  (user_id)
#

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :squeaks, dependent: :destroy
  has_many :relationships
  has_many :friends, through: :relationships
  
  has_many :inverse_relationships, class_name: "Relationship"
  has_many :inverse_friends, through: :inverse_relationships, source: :user 
  
  has_many :likes
  
  validates :username, presence: true, uniqueness: true
  
  def likes?(squeak)
    squeak.likes.where(user_id: id).any?
  end
end


# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string
#  username               :string
#  bio                    :text
#  location               :string
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_user_parameters, if: :devise_controller?
    

    protected
    
    def configure_permitted_user_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit( {roles: []}, :email, :password, :password_confirmation, :name, :username, :bio, :location)}
        
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit( :email, :password, :password_confirmation, :current_password, :name, :username, :bio, :location ) }
    end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_squeak
    
    def create
        @squeak.likes.where(user_id: current_user.id).first_or_create
        
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        @squeak.likes.where(user_id: current_user.id).destroy_all
        redirect_back(fallback_location: root_path)
    end
    
    
    private 
    
    def set_squeak
    @squeak = Squeak.find(params[:squeak_id])
    end
    
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    def index
        @users = User.all
    end
    
    def show
        @user = User.find(params[:id])
    end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    def create
        @relationship = current_user.relationships.build(friend_id: params[:friend_id])
        @friend = User.find(params[:friend_id])
        
        if @relationship.save
            flash[:notice] = "You've added #{@friend.username} to your nest."
            redirect_to profile_path(params[:friend_id])
        else
            flash[:notice] = "Something went wrong. Try again."
            redirect_to profile_path(params[:friend_id])
        end
    end
    
    def destroy
        @relationship = current_user.relationships.find(params[:id])
        @relationship.destroy 
        @exfriend = User.find(params[:friend_id])
        
        flash[:notice] = 'No longer following #{exfriend.username}.'
        redirect_to profile_path(current_user.id)
    end
    
    private
    
    def relationship_params #whitelist
        params.require(:relationship).permit(:user_id, :friend_id)
    
    end

end

app/controllers/squeaks_controller.rb
class SqueaksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_squeak, only: [:edit, :update, :show, :destroy]
  
  
  def index
    @squeaks = Squeak.all
  end

  def new #just puts up the form
    @squeak = Squeak.new
  end

  def create  
    @squeak = Squeak.new(squeak_params)
    
    if @squeak.save
      redirect_to @squeak, notice: "You squeaked!"
    else
      render :new #if squeak doesn't save, let's them try again. Goes back to 'new' method
    end
    
  end
  
  def edit
  end

  def update
    if @squeak.update(squeak_params)
      redirect_to @squeak, notice: 'You updated your squeak successfully.'
    else
      flash.now[:alert] = 'Something messed up. Try again.'
      render :edit
    end
  end

  def show
  end
  
  def destroy
    if @squeak.destroy
      redirect_to squeaks_path, notice: "Squeak deleted."
    else
      flash.now[:alert] = 'Something messed up. Try again.'
    end
  end
  
  private
  
  def squeak_params
    params.require(:squeak).permit(:message, :user_id)
  end
  
  def set_squeak
    @squeak = Squeak.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/squeaks_helper.rb
module SqueaksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mousy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/profiles/index.html.erb
<h1>All Users</h1>
<% @users.each do |user| %>
    <%= link_to user.username, profile_path(user) %><br>
<% end  %>

app/views/profiles/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-4">
            <h3><%= @user.name %></h3>
            <h5><%= @user.username %></h5>
            <h5><p><%= sanitize(@user.bio) %></p></h5>
            <h5><%= @user.location %></h5>
            <h5>Joined on <%= @user.created_at.stamp("November 1, 1999") %></h5>
            
            <%= @user.relationships.count %> following 
            <br>
            <% @user.relationships.each do |relationship|%>
                <%= link_to relationship.friend.name, profile_path(relationship.friend) %>
                <br>
            <% end  %>
            <br>
            <br>
            <%= pluralize(@user.inverse_relationships.count, "follower")  %>
            <br>
            
            <% @user.inverse_friends.each do |friend| %>
                <%= link_to friend.name, profile_path(friend) %><br>
            <% end  %>
        </div>
        
        <div class="col-7">
            <div class="card">
                <% @user.squeaks.each do |squeak| %>
                <div class="card-body">
                    <strong><%= squeak.user.username %> </strong><small>squeaked <%= time_ago_in_words(squeak.created_at)  %></small>
                    <br><br>
                    <%= squeak.message %>
                </div>
                <% end  %>
            </div>
        </div>
            
        
                
        <% if @user.id != current_user.id %>
        <% if current_user.friends.include?(@user) %>
            <%= link_to 'Unfollow', relationship_path(current_user.relationships.find_by_friend_id(@user), friend_id: @user), method: :delete, class: "btn btn-secondary mb-3" %>
        <% else %>
            <%= link_to 'Follow', relationships_path(friend_id: @user), method: :post, class: "btn btn-primary mb-3" %>
        <% end %>    
        <% end %>    
        
        <br>
        
        </div>
    </div>
</div>

app/views/shared/_likes.html.erb
<% if current_user.likes?(@squeak) %>
    <%= link_to 'Unlike', squeak_likes_path(@squeak), method: :delete %>    
<% else %>
    <%= link_to 'Like', squeak_likes_path(@squeak), method: :post %>
<% end %>

<%= pluralize(@squeak.likes.count, 'Like') %>
<br>

Liked by:

<% @squeak.likes.each do |like| %>
    <br>
    <%= like.user.username %>
    <br>
<% end %>

app/views/squeaks/_form.html.erb
<%= form_for(@squeak) do |f| %>
<!-- Check for errors -->
    <% if @squeak.errors.any?  %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@squeak.errors.count, 'error') %> stopped this squeak from being saved.
            </h2>
            <ul>
                <% @squeak.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
            
        </div>
    <% end %>

<!-- The Actual Form-->
    <div class="field form-group">
        <%= f.label :message %><br>
        <%= f.text_field :message, class: "form-control" %>
    </div>
    
    <div class="field form-group">
        <%= f.hidden_field :user_id, value: current_user.id, class: "form-control" %>
    </div>
    
    <div class="actions form-group">
        <%= f.submit class: "btn btn-info" %>
    </div>
    
<% end %>

app/views/squeaks/edit.html.erb
<h1>Edit Squeak</h1>

<%= render 'form' %>

<%= link_to 'Show all the Squeaks', squeak_path, class: "btn btn-secondary"%>

app/views/squeaks/index.html.erb
<div class="container">
    <div class="row text-center">
        <div class="col-md-4">
            <%= image_tag("MousyLogo.png")  %>
        </div>
         <div class="col-md-4 d-flex-column align-self-center p-2">
            <h1>ALL THE SQUEAKS</h1>
            <br><br>
            <%= link_to 'New Squeak', new_squeak_path, class: "btn btn-primary mb-3" %>
        </div>
         <div class="col-md-4">
             <%= image_tag("blank.png")  %>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <% @squeaks.order(created_at: :desc).each do |squeak|  %>
                <div class="card" style="margin-bottom: 1rem">
                    <div class="card-block" style="padding: 1rem; background-color: papayawhip;">
                        <p style="font-weight: bold"><%= squeak.message %></p>
                       
                        <%= squeak.user.try(:username) %>
                        <div class="pull-right">
                        <%= link_to fa_icon('eye', text: 'Show'),
                                squeak,
                                class: "btn btn-sm" %>
                        <%= link_to fa_icon('pencil', text: 'Edit'),
                                edit_squeak_path(squeak),
                                class: "btn btn-sm" %>
                        <%= link_to fa_icon('trash-o', text: 'Destroy'),
                                squeak,
                                method: :delete,
                                data:{confirm: 'Are you sure you want to delete this squeak?'},
                                class: "btn btn-sm" %></p>
                        </div>
                    </div>
                </div>
            <% end %>
        <div class="col-md-3"></div>
    </div>
</div>


<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>

app/views/squeaks/new.html.erb
<h1>New Squeak</h1>

<%= render 'form' %>

<%= link_to 'All the squeaks', squeaks_path, class: "btn btn-success" %>

app/views/squeaks/show.html.erb
<p>
    <strong>Message: </strong> <%= @squeak.message %>
    
</p>

<p>
    <strong>User: </strong> <%= @squeak.user.username %>
    
</p>

<%= render 'shared/likes' %>

<%= link_to 'Edit', edit_squeak_path(@squeak), class: 'btn btn-secondary' %>
<%= link_to 'Squeak History', squeaks_path, class: 'btn btn-primary' %>